https://huggingface.co/bert-base-uncased?text=Paris+is+the+%5BMASK%5D+of+France

In [1]:
from transformers import pipeline
unmasker = pipeline('fill-mask', model='bert-base-uncased')
unmasker("Hello I'm a [MASK] model.")

Downloading: 100%|██████████| 511M/511M [01:21<00:00, 6.54MB/s] 
2022-03-23 09:30:26.603913: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.
Downloading: 100%|██████████| 28.0/28.0 [00:00<00:00, 21.2kB/s]
Downloading: 100%|██████████| 226k/226k [00:00<00:00, 635kB/s] 
Downloading: 100%|██████████| 455k/455k [00:00<00:00, 912kB/s] 


[{'score': 0.10731048882007599,
  'token': 4827,
  'token_str': 'fashion',
  'sequence': "hello i'm a fashion model."},
 {'score': 0.08774499595165253,
  'token': 2535,
  'token_str': 'role',
  'sequence': "hello i'm a role model."},
 {'score': 0.05338373780250549,
  'token': 2047,
  'token_str': 'new',
  'sequence': "hello i'm a new model."},
 {'score': 0.046672090888023376,
  'token': 3565,
  'token_str': 'super',
  'sequence': "hello i'm a super model."},
 {'score': 0.0270958561450243,
  'token': 2986,
  'token_str': 'fine',
  'sequence': "hello i'm a fine model."}]

In [2]:
from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [5]:
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
array([[[ 0.1386269 ,  0.15826826, -0.29666448, ..., -0.27085   ,
         -0.28436255,  0.45808458],
        [ 0.5363638 , -0.23269653,  0.17542028, ...,  0.5540248 ,
          0.49807116, -0.00240775],
        [ 0.3002377 , -0.3475114 ,  0.12084441, ..., -0.45624927,
          0.32880142,  0.87728244],
        ...,
        [ 0.37985986,  0.12028724,  0.8282932 , ..., -0.86237264,
         -0.5956966 ,  0.04711615],
        [-0.02524163, -0.71767473, -0.69504786, ...,  0.07574159,
         -0.66678137, -0.3400743 ],
        [ 0.7535388 ,  0.23910952,  0.07174411, ...,  0.24671447,
         -0.64580613, -0.32129765]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.93767875, -0.5042591 , -0.979893  ,  0.90304404,  0.93293244,
        -0.24377501,  0.8925754 ,  0.22880591, -0.9531208 , -0.9999953 ,
        -0.8862302 ,  0.990

In [3]:

unmasker("The man worked as a [MASK].")

[{'score': 0.09747528284788132,
  'token': 10533,
  'token_str': 'carpenter',
  'sequence': 'the man worked as a carpenter.'},
 {'score': 0.05238311365246773,
  'token': 15610,
  'token_str': 'waiter',
  'sequence': 'the man worked as a waiter.'},
 {'score': 0.04962698742747307,
  'token': 13362,
  'token_str': 'barber',
  'sequence': 'the man worked as a barber.'},
 {'score': 0.03788597509264946,
  'token': 15893,
  'token_str': 'mechanic',
  'sequence': 'the man worked as a mechanic.'},
 {'score': 0.03768087550997734,
  'token': 18968,
  'token_str': 'salesman',
  'sequence': 'the man worked as a salesman.'}]

In [4]:
unmasker("The woman worked as a [MASK].")

[{'score': 0.21981306374073029,
  'token': 6821,
  'token_str': 'nurse',
  'sequence': 'the woman worked as a nurse.'},
 {'score': 0.1597401350736618,
  'token': 13877,
  'token_str': 'waitress',
  'sequence': 'the woman worked as a waitress.'},
 {'score': 0.11547201126813889,
  'token': 10850,
  'token_str': 'maid',
  'sequence': 'the woman worked as a maid.'},
 {'score': 0.03796864673495293,
  'token': 19215,
  'token_str': 'prostitute',
  'sequence': 'the woman worked as a prostitute.'},
 {'score': 0.030423592776060104,
  'token': 5660,
  'token_str': 'cook',
  'sequence': 'the woman worked as a cook.'}]