https://huggingface.co/bert-base-uncased?text=Paris+is+the+%5BMASK%5D+of+France

In [1]:
from transformers import pipeline
unmasker = pipeline('fill-mask', model='bert-base-uncased')
unmasker("Hello I'm a [MASK] model.")

2025-06-04 15:23:46.271064: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.
Device set to use 0


[{'score': 0.10731080919504166,
  'token': 4827,
  'token_str': 'fashion',
  'sequence': "hello i ' m a fashion model."},
 {'score': 0.08774475753307343,
  'token': 2535,
  'token_str': 'role',
  'sequence': "hello i ' m a role model."},
 {'score': 0.053383972495794296,
  'token': 2047,
  'token_str': 'new',
  'sequence': "hello i ' m a new model."},
 {'score': 0.046672094613313675,
  'token': 3565,
  'token_str': 'super',
  'sequence': "hello i ' m a super model."},
 {'score': 0.02709578163921833,
  'token': 2986,
  'token_str': 'fine',
  'sequence': "hello i ' m a fine model."}]

In [2]:
from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [3]:
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
array([[[ 0.1386273 ,  0.15826872, -0.29666477, ..., -0.27084953,
         -0.2843629 ,  0.45808473],
        [ 0.5363635 , -0.23269637,  0.17541927, ...,  0.55402505,
          0.49807125, -0.00240827],
        [ 0.300238  , -0.34751162,  0.12084398, ..., -0.4562487 ,
          0.3288021 ,  0.8772818 ],
        ...,
        [ 0.3798591 ,  0.12028816,  0.82829344, ..., -0.8623719 ,
         -0.59569687,  0.0471146 ],
        [-0.02524215, -0.71767503, -0.6950478 , ...,  0.07574263,
         -0.6667813 , -0.34007427],
        [ 0.7535381 ,  0.2391096 ,  0.07174394, ...,  0.24671488,
         -0.64580667, -0.32129782]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.93767864, -0.5042589 , -0.9798931 ,  0.9030441 ,  0.93293256,
        -0.2437751 ,  0.8925754 ,  0.22880596, -0.9531208 , -0.99999535,
        -0.88623023,  0.990

In [4]:

unmasker("The man worked as a [MASK].")

[{'score': 0.09747539460659027,
  'token': 10533,
  'token_str': 'carpenter',
  'sequence': 'the man worked as a carpenter.'},
 {'score': 0.052383072674274445,
  'token': 15610,
  'token_str': 'waiter',
  'sequence': 'the man worked as a waiter.'},
 {'score': 0.049626950174570084,
  'token': 13362,
  'token_str': 'barber',
  'sequence': 'the man worked as a barber.'},
 {'score': 0.037885986268520355,
  'token': 15893,
  'token_str': 'mechanic',
  'sequence': 'the man worked as a mechanic.'},
 {'score': 0.03768088296055794,
  'token': 18968,
  'token_str': 'salesman',
  'sequence': 'the man worked as a salesman.'}]

In [5]:
unmasker("The woman worked as a [MASK].")

[{'score': 0.21981395781040192,
  'token': 6821,
  'token_str': 'nurse',
  'sequence': 'the woman worked as a nurse.'},
 {'score': 0.15974003076553345,
  'token': 13877,
  'token_str': 'waitress',
  'sequence': 'the woman worked as a waitress.'},
 {'score': 0.11547227203845978,
  'token': 10850,
  'token_str': 'maid',
  'sequence': 'the woman worked as a maid.'},
 {'score': 0.037968508899211884,
  'token': 19215,
  'token_str': 'prostitute',
  'sequence': 'the woman worked as a prostitute.'},
 {'score': 0.03042360208928585,
  'token': 5660,
  'token_str': 'cook',
  'sequence': 'the woman worked as a cook.'}]