https://huggingface.co/gpt2?text=A+long+time+ago%2C

In [1]:
from transformers import pipeline, set_seed




In [2]:
generator = pipeline('text-generation', model='gpt2')

2022-03-23 10:17:13.157439: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-23 10:17:13.167112: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [3]:
set_seed(42)
generator("Hello, I'm a language model,", max_length=30, num_return_sequences=5)

Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence


[{'generated_text': "Hello, I'm a language model, I'm talking about the language model, not a computer model, which makes sense that, like I said,"},
 {'generated_text': "Hello, I'm a language model, and your first question is if this is possible or not? I don't know. Maybe this is your goal"},
 {'generated_text': "Hello, I'm a language model, so there's no need to write some boilerplate code, but that means that you really need nothing more than"},
 {'generated_text': 'Hello, I\'m a language model, a mathematical model... I\'m gonna write something called a "math model" because the basic idea is. Why'},
 {'generated_text': "Hello, I'm a language model, the model you got from this article. This is basically something I learned from my other courses by talking to people"}]

In [4]:
# "The Appointment in Samarra"
# https://www.k-state.edu/english/baker/english320/Maugham-AS.htm
generator(
    """I will go to Samarra and there Death will not find me.""", 
     max_length=100, 
     num_return_sequences=5)

Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence


[{'generated_text': 'I will go to Samarra and there Death will not find me. I shall never go there.\n\nIn response to this question the author stated that he knew nothing about her whereabouts, but that he did know when she was abducted, and that the authorities may seek to recover her corpse. However, he suggested that the authorities should seek to find her body for burial, and then proceed with that to the point where the person could be identified, without using any of the previous information which led to'},
 {'generated_text': 'I will go to Samarra and there Death will not find me. In all my life I have been here in Jerusalem. I shall go to a place in Jerusalem called Mount Anas and there be no life except the life of the Lord."\n\nNow, some Christians have been trying to make themselves heard, especially among children. But they have been caught in error. In Israel\'s ancient days the Jews were called Shagruv, like our ancient fathers in the desert. So it is'},
 {'generated_text

In [5]:
generator(
    """To make a good beef stew you must first""", 
     max_length=100, 
     num_return_sequences=5)

Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence


[{'generated_text': "To make a good beef stew you must first boil the vegetables, add the vinegar then add the sugar and let it all simmer for about 4 minutes, about 1 minute longer than your own. It'll look something like this: 1,742 g pork sausage\n\n1,742 g beef chuck\n\n1/4 inch salt and pepper\n\n1 pound minced garlic\n\n4 cups vegetable broth\n\n1/4 teaspoon ground cumin\n\n1 tsp cayenne pepper\n"},
 {'generated_text': "To make a good beef stew you must first make it cold: the ingredients for a beef stew are a combination of salt and water, which are important to keep in stock.\n\nFor this recipe I cooked it in water and placed it under a cover. The cover is on the inside of the cookware so you can't peek at the sauce. I like to make the sauce that way since it will keep in the fridge for a while. Then it is ready to use.\n\nThen"},
 {'generated_text': 'To make a good beef stew you must first get rid of all the excess fat from the meat and take a long, hard hard bite. If you take

In [6]:
from transformers import GPT2Tokenizer, TFGPT2Model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = TFGPT2Model.from_pretrained('gpt2')
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)



All model checkpoint layers were used when initializing TFGPT2Model.

All the layers of TFGPT2Model were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2Model for predictions without further training.


In [7]:
output

TFBaseModelOutputWithPastAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 10, 768), dtype=float32, numpy=
array([[[ 0.16290504, -0.21657321, -0.14102796, ..., -0.26188612,
         -0.08190862,  0.00923965],
        [ 0.46279636,  0.02483824, -0.07853653, ..., -0.08585865,
          0.5122231 , -0.39390516],
        [-0.0643688 ,  0.15511855, -0.6305846 , ...,  0.24878435,
          0.36905357,  0.08326841],
        ...,
        [-0.5590803 , -0.4490242 , -1.4539901 , ...,  0.16498974,
         -0.13022897, -0.37402728],
        [ 0.14001578, -0.38752836, -0.79156166, ..., -0.17796862,
          0.18236083,  0.21849144],
        [ 0.17207055, -0.24204691, -0.11238737, ..., -0.10684221,
          0.12054701, -0.3212943 ]]], dtype=float32)>, past_key_values=(<tf.Tensor: shape=(2, 1, 12, 10, 64), dtype=float32, numpy=
array([[[[[-1.07186723e+00,  2.41698933e+00,  9.66034234e-01, ...,
           -4.78705734e-01, -3.31557035e-01,  1.79252326e+00],
          [-2.28969359e+00,  2.54